### ISSUE TITLE
Update plugin minimum versions in pubspec.yaml

### ISSUE THREAD

**Issue by LarkAscending** [flutter/friendlychat-steps#41]
The sample pubspec.yaml file in the [full_steps/step_1 folder](https://github.com/flutter/friendlychat-steps/blob/master/full_steps/step_1_set_up_firebase/pubspec.yaml) needs updating to point to the latest plugin versions:
```
dependencies:
  flutter:
    sdk: flutter
  image_picker: 0.1.0 -> 0.1.1
  google_sign_in: 0.3.1
  firebase_analytics: 0.0.4
  firebase_auth: 0.1.1 -> 0.2.0
  firebase_database: 0.0.12
  firebase_storage: 0.0.5
```
[Step 5 of the Firebase Codelab](https://codelabs.developers.google.com/codelabs/flutter-firebase/index.html#4) has the updated versions. The sample config file in this repo needs updating to match the codelab.

/cc @collinjackson @efortuna @emshack
